/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      AudioStreamTests.hpp                       ||
||     Author:    Autogenerated                              ||
||     Generated: 30.01.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _AudioStreamTests_hpp_
#define _AudioStreamTests_hpp_

#include "TestCaseBase.hpp"

namespace Wave {   
    namespace Test {
        class AudioStreamTests : public PerTypeTests<AbstractAudioStream*>
        {
        public:
            AudioStreamTests(void);
            virtual ~AudioStreamTests(void);
            virtual void AddTestCasesPerTypeCase( DynamicStrait<AbstractAudioStream*>* testcases ) override;

        protected:
            virtual int  runTestCase(AbstractAudioStream* frametype) override;
        };
    }
} //end of Wave

#endif
