/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      AudioStreamTests.cpp                       ||
||     Author:    Autogenerated                              ||
||     Generated: 30.01.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#include "AudioStreamTests.hpp"

Wave::Test::AudioStreamTests::AudioStreamTests(void) : PerTypeTests()
{

}

Wave::Test::AudioStreamTests::~AudioStreamTests(void)
{
    cases.Clear( true );
    PerTypeTests::~PerTypeTests();
}

int
Wave::Test::AudioStreamTests::runTestCase(AbstractAudioStream* instance)
{
    switch ( instance->GetDirection() ) {
    case StreamDirection::READ: {
        // WaveReader
    } break;
    case StreamDirection::WRITE: {
        // WaveWriter
    } break;
    case StreamDirection::INOUT: {
        // StreamBuffer 
    } break;
    }
    return 1000;
}

void
Wave::Test::AudioStreamTests::AddTestCasesPerTypeCase( DynamicStrait<AbstractAudioStream*>* testcases ) 
{
    testcases->Add(new WaveFileReader());
    testcases->Add(new WaveFileWriter());
    testcases->Add(new AudioStream(44100, 24, 2, 1024));
}
