/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      BufferConversionTests.hpp                  ||
||     Author:    Autogenerated                              ||
||     Generated: 30.01.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _BufferConversionTests_hpp_
#define _BufferConversionTests_hpp_

#include "TestCaseBase.hpp"

namespace Wave {
    namespace Test {
        class BufferConversionTests : public PerFrameType
        {
        public:
            BufferConversionTests(void);
            virtual ~BufferConversionTests(void);
        
        protected:
            // Geerbt über PerTypeTests
            virtual int runTestCase( const AudioFrameType* frametype ) override;
        };
    }
} //end of Wave

#endif
