/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      BufferConversionTests.cpp                  ||
||     Author:    Autogenerated                              ||
||     Generated: 30.01.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#include "BufferConversionTests.hpp"

Wave::Test::BufferConversionTests::BufferConversionTests(void) : PerFrameType()
{

}

Wave::Test::BufferConversionTests::~BufferConversionTests(void)
{
    cases.Clear();
}

int
Wave::Test::BufferConversionTests::runTestCase(const AudioFrameType* frametype)
{
    return 1000;
}

