/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      ByFrameApi.hpp                             ||
||     Author:    Autogenerated                              ||
||     Generated: 01.11.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _ByFrameApi_hpp_
#define _ByFrameApi_hpp_

#include "TestCaseBase.hpp"

namespace Wave {
    namespace Test {

        class ByFrameApi : public PerFrameType
        {
        public:
            byte testdata[128];
            ByFrameApi(void);
            virtual ~ByFrameApi(void);
        protected:
            virtual int runTestCase(const AudioFrameType* frametype) override;
        };

    } //end of Wave
}
#endif
