/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      PamHeaderTests.hpp                         ||
||     Author:    Autogenerated                              ||
||     Generated: 02.01.2022                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _PamHeaderTests_hpp_
#define _PamHeaderTests_hpp_

#include "AudioStreamTests.hpp"

namespace Wave {
    namespace Test {
        class PamHeaderTests : public PerFrameType 
        {
        public:
            WaveFileWriter  writer;
            Audio           buffer;
            int             failed;
            PamHeaderTests(void);
            virtual ~PamHeaderTests(void);

        protected:
            virtual int runTestCase( const AudioFrameType* frametype ) override;
            int testSaveToPamFormat( const AudioFrameType* frametype );
            int testLoadingPamFiles( const AudioFrameType* frametype );
        };
    } //end of Wave
}
#endif
