/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      SplittingTests.cpp                         ||
||     Author:    Autogenerated                              ||
||     Generated: 30.01.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#include "SplittingTests.hpp"

Wave::Test::SplittingTests::SplittingTests(void) : PerFrameType()
{

}

Wave::Test::SplittingTests::~SplittingTests(void)
{
    // TODO: implement what ever you think...
}

int 
Wave::Test::SplittingTests::runTestCase(const AudioFrameType* frametype)
{
    return 1000;
}

