/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      SplittingTests.hpp                         ||
||     Author:    Autogenerated                              ||
||     Generated: 30.01.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _SplittingTests_hpp_
#define _SplittingTests_hpp_

#include "TestCaseBase.hpp"

namespace Wave {    
    namespace Test {
        class SplittingTests : public PerFrameType
        {
        public:
            SplittingTests(void);
            virtual ~SplittingTests(void);

        protected:
            // Geerbt über PerTypeTests
            virtual int runTestCase(const AudioFrameType* frametype) override;
        };
    }
} //end of Wave

#endif
