/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      trimming216.h                              ||
||     Author:    Autogenerated                              ||
||     Generated: 11.03.2021                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _TrimTrom_Resource_Included_
#define _TrimTrom_Resource_Included_
#ifdef __cplusplus
extern "C" {
#endif

    RESOURCE_DATA_ACCES(trimming216);

#ifdef __cplusplus
}
#endif
#endif
