/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      trimming108.h                              ||
||     Author:    Autogenerated                              ||
||     Generated: 03.11.2020                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef _trimming108_Resource_Included_
#define _trimming108_Resource_Included_
#ifdef __cplusplus
extern "C" {
#endif

RESOURCE_DATA_ACCES(trimming108);

#ifdef __cplusplus
}
#endif
#endif
